### ISSUE TITLE
怎么没引进sass

### ISSUE THREAD

**Issue by Pillar-Zhang** [JoV5/react-starter#2]

**Comment by JoV5** [comment]
https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-a-css-preprocessor-sass-less-etc

**Comment by Pillar-Zhang** [comment]
之前在用webpack1的时候 scss 不都是用loader 直接引进 到webpack.config 里面处理的么？之前一直都是那么用的 现在为什么要在外面编译后再引入？这样有什么好处么？

**Comment by JoV5** [comment]
应该是一样的，可能这样改起来更方便？我没加只是想和官方保持一致。
